plugins { id 'java' }

group = 'com.example'
version = '1.0.0'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

repositories { mavenCentral() }

dependencies {
    compileOnly files('libs/hzkmacros-module-api-4.0.jar')
    compileOnly files('libs/hello-provider-1.0.0.jar')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    archiveBaseName = 'hello-consumer'
}
